import { Mail, Phone, MapPin } from "lucide-react";
import { FaFacebookF, FaInstagram, FaLinkedinIn, FaYoutube } from "react-icons/fa";
import { Link } from "react-router-dom";
import studyPointLogo from "../accests/studyPointLogo.jpeg";

export default function Footer() {
  return <footer className="mt-20 bg-slate-950 text-slate-300">
    <div className="container-x grid gap-10 py-14 md:grid-cols-4">
      <div className="md:col-span-2"><Link to="/" className="mb-4 inline-flex items-center gap-2 text-xl font-extrabold text-white"><img src={studyPointLogo} alt="Study Point Logo" className="h-11 w-11 rounded-full object-contain"/>Study Point</Link><p className="max-w-md text-slate-400">A modern learning platform built to help students learn smarter, practice consistently and achieve their goals.</p><div className="mt-6 flex items-center gap-3"><a href="https://www.facebook.com/people/Study-Point/61573495199501/#" target="_blank" rel="noreferrer" aria-label="Study Point on Facebook" title="Facebook" className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-slate-700 text-slate-300 transition hover:border-blue-500 hover:bg-blue-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400"><FaFacebookF size={17}/></a><a href="https://www.instagram.com/study_point_bhubaneswar?igsi=djNtbms5cGNtbW9l" target="_blank" rel="noreferrer" aria-label="Study Point on Instagram" title="Instagram" className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-slate-700 text-slate-300 transition hover:border-pink-500 hover:bg-pink-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400"><FaInstagram size={18}/></a><a href="https://www.youtube.com/" target="_blank" rel="noreferrer" aria-label="Study Point on YouTube" title="YouTube" className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-slate-700 text-slate-300 transition hover:border-red-500 hover:bg-red-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400"><FaYoutube size={18}/></a><a href="https://www.linkedin.com/" target="_blank" rel="noreferrer" aria-label="Study Point on LinkedIn" title="LinkedIn" className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-slate-700 text-slate-300 transition hover:border-sky-500 hover:bg-sky-500 hover:text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400"><FaLinkedinIn size={17}/></a></div></div>
      <div><h4 className="mb-4 font-bold text-white">Quick Links</h4><nav className="flex flex-col items-start gap-2 text-sm"><Link to="/" className="hover:text-white">Home</Link><Link to="/courses" className="hover:text-white">Courses</Link><Link to="/about" className="hover:text-white">About</Link><Link to="/contact" className="hover:text-white">Contact</Link></nav></div>
      <div><h4 className="mb-4 font-bold text-white">Contact</h4><div className="space-y-3 text-sm"><p className="flex items-start gap-2"><Phone className="mt-0.5 shrink-0" size={16}/><span><a href="tel:8280971995" className="hover:text-white">8280971995</a><br/><a href="tel:8763464066" className="hover:text-white">8763464066</a></span></p><p className="flex items-start gap-2"><Mail className="mt-0.5 shrink-0" size={16}/><a href="mailto:studypointbbsr@gmail.com" className="break-all hover:text-white">studypointbbsr@gmail.com</a></p><p className="flex items-start gap-2"><MapPin className="mt-0.5 shrink-0" size={16}/><a href="https://maps.google.com/?q=Plot+No+HIG-87+K-6+Kalinga+Vihar+Bhubaneshwar" target="_blank" rel="noreferrer" className="hover:text-white">Plot No: HIG-87, K-6, Kalinga Vihar,<br/>Bhubaneshwar</a></p></div></div>
    </div><div className="border-t border-slate-800 py-5 text-center text-sm text-slate-500">© {new Date().getFullYear()} Study Point. All rights reserved.</div>
  </footer>
}
