import { useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../services/api";
import { ArrowRight, BarChart3, Check, ChevronDown, Heart, LineChart, Phone, Sparkles, Target, Users } from "lucide-react";
import HeroVideo from "../components/media/HeroVideo";
import VideoCard from "../components/media/VideoCard";
import VideoModal from "../components/media/VideoModal";
import admissionPoster from "../accests/WhatsApp Image 2026-08-24 at 12.57.05 PM.jpeg";
import classroomPoster from "../accests/WhatsApp Image 2026-08-24 at 12.57.04 PM.jpeg";
import resultsPoster from "../accests/WhatsApp Image 2026-08-24 at 12.57.05 PM (1).jpeg";
import classroomVideo from "../accests/A_realistic_cinematic_scene_in.mp4";
import motivationVideo from "../accests/AI_Video_Generator_Prompt_Veo.mp4";

const videos = [{ title: "Study Point classroom", src: classroomVideo, poster: classroomPoster }, { title: "Study Point motivation", src: motivationVideo, poster: admissionPoster }];
const programs = [["VI-VIII", "Foundation Program", "Build strong fundamentals with a steady academic rhythm.", "All subjects"], ["IX-X", "Board Excellence", "Concept clarity, regular practice and exam-ready preparation.", "CBSE / ICSE / CHSE"], ["XI-XII", "Science Program", "Focused senior-school support for ambitious learners.", "Science stream"], ["JEE", "JEE Foundation", "Build the problem-solving base for engineering entrances.", "Physics / Chemistry / Maths"], ["NEET", "NEET Foundation", "A structured path for biology-led entrance preparation.", "Physics / Chemistry / Biology"], ["Foundation", "Board Exam Mastery", "Personalised academic support from classwork to mock tests.", "VI-XII"]];
const faqs = ["Which classes does Study Point teach?", "Which boards are covered?", "Do you offer JEE preparation?", "Do you offer NEET preparation?", "Are regular tests conducted?", "How can I apply for admission?", "Where is Study Point located?"];
function Intro({ label, title, children, light = false }) { return <div className={`max-w-2xl ${light ? "text-white" : ""}`}><p className="eyebrow">{label}</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight sm:text-5xl">{title}</h2>{children && <p className={`mt-4 text-lg leading-8 ${light ? "text-blue-100" : "text-slate-500"}`}>{children}</p>}</div>; }

export default function Home() {
  const [openVideo, setOpenVideo] = useState(null); const [openFaq, setOpenFaq] = useState(null); const [form, setForm] = useState({ name: "", email: "", phone: "", course: "", message: "" }); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  const submit = async (event) => { event.preventDefault(); setError(""); try { await api.post("/enquiries", form); setSent(true); setForm({ name: "", email: "", phone: "", course: "", message: "" }); } catch (err) { setError(err.response?.data?.message || "Unable to submit. Please try again."); } };
  return <div className="overflow-hidden">
    <section className="hero-band text-white"><div className="container-x relative grid min-h-[700px] items-center gap-16 py-20 lg:grid-cols-[1fr_.9fr]"><div className="reveal"><p className="eyebrow text-yellow-300">2026-27 admissions open</p><h1 className="mt-5 max-w-3xl text-5xl font-extrabold leading-[1.03] tracking-tight sm:text-7xl">Shape your future with the <span className="text-yellow-300">right guidance.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-blue-100">Expert teaching, structured learning, regular assessments and personalised guidance for students from VI to XII.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/courses" className="btn-gold">Explore Courses <ArrowRight size={18}/></Link><Link to="/contact" className="btn-outline">Apply for Admission</Link></div><div className="mt-8 flex flex-wrap gap-6 text-sm font-semibold text-blue-100"><a href="tel:8280971995" className="inline-flex items-center gap-2"><Phone size={16}/>8280971995</a><a href="tel:8763464066" className="inline-flex items-center gap-2"><Phone size={16}/>8763464066</a></div></div><div className="reveal reveal-delay"><HeroVideo video={videos[0]} onOpen={setOpenVideo}/></div></div></section>
    <section className="border-b border-slate-200 bg-white"><div className="container-x trust-strip"><div><strong>10+</strong><span>Years of excellence</span></div><div><strong>5000+</strong><span>Students guided</span></div><div><strong>25+</strong><span>Expert faculty</span></div><div><strong>95%+</strong><span>Success focus</span></div><div><strong>VI-XII</strong><span>Academic programs</span></div></div></section>
    <section className="container-x section-pad"><Intro label="Why Study Point" title="Learning designed around student success">More than classes. A complete learning ecosystem designed to help students understand, practise and improve.</Intro><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Users,"01","Expert Faculty"],[Heart,"02","Personalised Attention"],[BarChart3,"03","Regular Tests"],[LineChart,"04","Performance Analysis"],[Target,"05","Strong Concept Building"],[Target,"06","Result-Oriented Preparation"]].map(([Icon, number, title]) => <div className="feature-block" key={title}><span className="feature-number">{number}</span><Icon className="text-blue-700" size={25}/><h3 className="mt-7 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">A thoughtful, consistent approach that keeps progress visible.</p></div>)}</div></section>
    <section className="story-band"><div className="container-x grid items-center gap-12 py-24 lg:grid-cols-[1.05fr_.95fr]"><div className="relative"><img src={classroomPoster} alt="Study Point classroom with students" loading="lazy" className="h-[520px] w-full rounded-[2rem] object-cover shadow-2xl"/><div className="absolute -bottom-6 -right-4 max-w-[220px] rounded-2xl bg-yellow-400 p-5 font-bold text-[#071A41] shadow-xl"><Sparkles size={22}/><p className="mt-3">A habit of learning creates a future of choices.</p></div></div><div><Intro label="Inside Study Point" title="A place where learning becomes a habit.">From classroom teaching to regular assessments and personalised guidance, Study Point focuses on building confident and capable students.</Intro><div className="mt-8 grid gap-3 sm:grid-cols-2">{["Experienced faculty", "Regular practice", "Personal attention", "Doubt support", "Performance tracking"].map(item => <p className="flex items-center gap-3 font-semibold text-slate-700" key={item}><span className="grid h-7 w-7 place-items-center rounded-full bg-blue-100 text-blue-700"><Check size={15}/></span>{item}</p>)}</div><Link to="/about" className="mt-9 inline-flex items-center gap-2 font-bold text-blue-700">Discover Study Point <ArrowRight size={18}/></Link></div></div></section>
    <section className="container-x section-pad"><div className="flex flex-wrap items-end justify-between gap-6"><Intro label="Real Study Point story" title="Experience Study Point">Real classrooms, real milestones and the energy behind the work.</Intro><Link to="/contact" className="hidden font-bold text-blue-700 sm:inline-flex sm:items-center sm:gap-2">Visit our centre <ArrowRight size={18}/></Link></div><div className="media-grid mt-12"><VideoCard video={videos[1]} onOpen={setOpenVideo} className="media-large"/><img src={admissionPoster} alt="Study Point admission open poster" loading="lazy" className="media-image media-poster"/><img src={resultsPoster} alt="Study Point board result achievers" loading="lazy" className="media-image media-poster"/></div></section>
    <section className="results-band text-white"><div className="container-x grid items-center gap-14 py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-yellow-300">Student success</p><h2 className="mt-4 text-6xl font-extrabold text-yellow-300 sm:text-8xl">95%<span className="text-4xl">+</span></h2><h3 className="mt-2 text-2xl font-bold">Success focus</h3><p className="mt-5 max-w-md leading-7 text-blue-100">Every student receives structured guidance, regular practice and performance feedback.</p></div><div><Intro light label="Our students make us proud" title="Celebrating hard work, consistency and academic excellence."/><img src={resultsPoster} alt="Study Point board results and top performers" loading="lazy" className="mt-10 h-[380px] w-full rounded-2xl object-cover shadow-2xl"/></div></div></section>
    <section className="faq-band section-pad"><div className="container-x grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><Intro label="Questions, answered" title="Start with clarity">The essentials for students and parents considering Study Point.</Intro><div className="divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white px-6">{faqs.map((question, index) => <div key={question}><button type="button" className="flex w-full items-center justify-between gap-4 py-5 text-left font-bold text-slate-900" aria-expanded={openFaq === index} onClick={() => setOpenFaq(openFaq === index ? null : index)}>{question}<ChevronDown size={19} className={openFaq === index ? "rotate-180 transition" : "transition"}/></button>{openFaq === index && <p className="pb-5 text-sm leading-6 text-slate-500">Our counselling team can share the latest details for this question. Send an enquiry and we will help you plan the next step.</p>}</div>)}</div></div></section>
    <section className="container-x section-pad" id="contact"><div className="grid gap-12 rounded-[2rem] bg-slate-50 p-7 sm:p-12 lg:grid-cols-[.8fr_1.2fr]"><div><Intro label="Let's build your future together" title="Talk to our counselling team">Plot No: HIG-87, K-6, Kalinga Vihar, Bhubaneswar</Intro><div className="mt-8 space-y-3 font-bold"><a className="flex items-center gap-3" href="tel:8280971995"><Phone className="text-blue-700" size={19}/>8280971995</a><a className="flex items-center gap-3" href="tel:8763464066"><Phone className="text-blue-700" size={19}/>8763464066</a></div></div>{sent ? <div className="flex min-h-64 flex-col justify-center rounded-2xl bg-emerald-50 p-7 text-emerald-800"><h3 className="text-xl font-bold">Enquiry submitted successfully.</h3><p className="mt-2">Our team will contact you soon.</p></div> : <form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><input required placeholder="Student name" value={form.name} onChange={e => setForm({...form, name: e.target.value})}/><input required type="email" placeholder="Email address" value={form.email} onChange={e => setForm({...form, email: e.target.value})}/><input placeholder="Phone number" value={form.phone} onChange={e => setForm({...form, phone: e.target.value})}/><select value={form.course} onChange={e => setForm({...form, course: e.target.value})}><option value="">Interested program</option>{programs.map(([, title]) => <option key={title}>{title}</option>)}</select><textarea className="sm:col-span-2" rows="4" placeholder="How can we help?" value={form.message} onChange={e => setForm({...form, message: e.target.value})}/>{error && <p className="sm:col-span-2 text-sm text-red-600">{error}</p>}<button className="btn-primary sm:col-span-2">Request counselling <ArrowRight size={18}/></button></form>}</div></section>
    <a href="tel:8280971995" className="mobile-cta"><Phone size={17}/>Call us</a><Link to="/contact" className="mobile-cta mobile-cta-gold">Apply now <ArrowRight size={17}/></Link>{openVideo && <VideoModal video={openVideo} onClose={() => setOpenVideo(null)}/>} 
  </div>;
}
