import { Link } from "react-router-dom";
import { ArrowRight, Award, BookOpen, CheckCircle2, GraduationCap, Users } from "lucide-react";
import { catalogCourses } from "../data/courses";
export default function Home() {
 return <div className="home-page">
  <section className="home-hero relative overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_30%,rgba(79,70,229,.35),transparent_35%)]"/><div className="container-x relative grid min-h-[620px] items-center gap-10 py-20 lg:grid-cols-2"><div className="home-hero-copy"><span className="mb-5 inline-flex rounded-full border border-amber-400/30 bg-amber-400/10 px-4 py-2 text-sm font-semibold text-amber-300">Admissions Open: 2026–27 Batch</span><h1 className="max-w-3xl text-5xl font-extrabold leading-tight tracking-tight sm:text-6xl">Shape your future with <span className="text-indigo-400">Study Point.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-300">Classes VI to XII for all subjects, with CBSE, ICSE and CHSE support plus focused JEE, NEET and Foundation preparation.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/courses" className="btn-primary">Explore Courses <ArrowRight size={18}/></Link><Link to="/contact" className="rounded-xl border border-slate-700 px-5 py-3 font-semibold text-white hover:bg-white/5">Admission Enquiry</Link></div><div className="mt-10 flex gap-8 text-sm text-slate-300"><span><b className="text-2xl text-white">VI–XII</b><br/>All Subjects</span><span><b className="text-2xl text-white">5.0</b><br/>170 Reviews</span><span><b className="text-2xl text-white">25+</b><br/>Expert Faculty</span></div></div><div className="home-hero-visual hidden lg:block"><div className="mx-auto max-w-md rounded-[2rem] border border-white/10 bg-white/10 p-3 shadow-2xl backdrop-blur"><img className="h-[430px] w-full rounded-[1.5rem] object-cover" src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1000&q=85" alt="Students learning"/></div></div></div></section>
    <section className="container-x py-16"><div className="max-w-4xl"><p className="font-semibold text-indigo-600">Study Point in Kalinga Vihar, Bhubaneshwar</p><h2 className="mt-2 text-3xl font-extrabold">A trusted place to learn, grow and succeed.</h2><p className="mt-4 leading-7 text-slate-600">Study Point in Kalinga Vihar, Bhubaneshwar is a renowned education institution that has been offering high-quality coaching services for many years. Specializing in Tutorials and a wide range of academic and competitive exam preparations, the institute has become a trusted destination for students looking to achieve academic success. Rated 5.0 based on 170 reviews, it is known for its supportive learning environment and experienced educators.</p><div className="mt-7 grid gap-5 sm:grid-cols-3"><div className="card p-5"><h3 className="font-bold">Classes Offered</h3><p className="mt-2 text-sm leading-6 text-slate-500">Courses tailored for students across different academic levels.</p></div><div className="card p-5"><h3 className="font-bold">Expert Faculty</h3><p className="mt-2 text-sm leading-6 text-slate-500">Experienced teachers who help students excel in their studies.</p></div><div className="card p-5"><h3 className="font-bold">Student Support</h3><p className="mt-2 text-sm leading-6 text-slate-500">Library, doubt clearing, online resources, counseling and mock tests.</p></div></div></div></section>
  <section className="home-features container-x py-20"><div className="grid gap-5 md:grid-cols-3">{[[BookOpen,"Structured Learning","Clear courses, subjects and learning paths."],[Users,"Expert Guidance","Learn with experienced and supportive faculty."],[Award,"Progress Focused","Practice, tests and feedback to keep improving."]].map(([Icon,t,d])=><div className="card p-7" key={t}><span className="mb-5 grid h-12 w-12 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon/></span><h3 className="text-lg font-bold">{t}</h3><p className="mt-2 text-slate-500">{d}</p></div>)}</div></section>
  <section className="home-courses bg-white py-20"><div className="container-x"><div className="flex items-end justify-between gap-5"><div><p className="font-semibold text-indigo-600">Popular programs</p><h2 className="mt-2 text-3xl font-extrabold">Courses designed for results</h2></div><Link to="/courses" className="hidden font-semibold text-indigo-600 sm:block">View all →</Link></div><div className="mt-8 grid gap-6 md:grid-cols-3">{catalogCourses.slice(0, 3).map(c=><article className="home-course-card card overflow-hidden" key={c.title}><img src={c.image} className="h-48 w-full object-cover" alt={c.title}/><div className="p-6"><div className="flex justify-between text-xs font-semibold text-indigo-600"><span>{c.category}</span><span>{c.duration}</span></div><h3 className="mt-3 text-xl font-bold">{c.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{c.description}</p><div className="mt-5 flex justify-end"><Link to="/courses" className="font-semibold text-indigo-600">Details →</Link></div></div></article>)}</div></div></section>
  <section className="home-cta container-x py-20"><div className="rounded-3xl bg-indigo-600 p-8 text-white sm:p-12"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><h2 className="text-3xl font-extrabold">Admissions are open for 2026–27</h2><p className="mt-3 max-w-xl text-indigo-100">Call <a href="tel:8280971995" className="font-bold underline">8280971995</a> or <a href="tel:8763464066" className="font-bold underline">8763464066</a> for admission enquiries and course guidance.</p></div><div className="flex lg:justify-end"><Link to="/contact" className="rounded-xl bg-white px-6 py-3 font-bold text-indigo-700">Admission Enquiry</Link></div></div></div></section>
 </div>
}